### ISSUE TITLE
Correção dos Casos de Uso

### ISSUE THREAD

**Issue by paulhenrique** [ICEI-PUC-Minas-PMV-SInt/pmv-sint-2023-1-e3-proj-back-t1-time4-projroadmap#11]
**Compreender os usuários e definir uma proposta de solução centrada nos usuários:** 
elaborar diagramas de caso de uso da aplicação.

**Comment by Silva-Cesar** [comment]
**Comentário do professor:**
"O diagrama entregue não contempla a descrição do perfil/papel do ator e as linhas tracejadas não contemplam os estereótipos. Também não existem sentidos(setas) bidirecionais em relação a um mesmo relacionamento. Tenho dúvidas em relação a existência de relacionamentos entre alguns casos de uso (Vou precisar conversar com vocês para ter mais clareza).
O diagrama entregue contempla apenas um ator, mas o problema envolve outros atores. Exemplo: Quem cadastra as questões é um ator diferente do desenvolvedor que quer acessar/visualizar/responder as questões."
