### ISSUE TITLE
Correção das Histórias de Usuário

### ISSUE THREAD

**Issue by paulhenrique** [ICEI-PUC-Minas-PMV-SInt/pmv-sint-2023-1-e3-proj-back-t1-time4-projroadmap#12]
**Compreender os usuários e definir uma proposta de solução centrada nos usuários:** 
categorizar requisitos funcionais e não funcionais derivados de histórias de usuários.

**Comment by Silva-Cesar** [comment]
**Comentário do professor:**
"As histórias de usuário descritas no trabalho não foram levantadas no sentido retratar anseios dos usuários em relação as funcionalidades desejáveis da solução tecnológica. É necessário levantar/complementar novas histórias de usuários.
Alguns RFs especificados não derivaram das histórias dos usuários. Mesmo que o analista vislumbre a necessidade de um RF, ele tem que investigar com os usuários se o RF vislumbrado realmente é importante e necessário no contexto do projeto. Caso a importância se confirme, a narrativa do usuário deve ser incluída nas histórias, de modo que todos os RFs derivem das histórias elencadas.
Alguns RFs contemplam aspectos de design e não funcionalidades do sistema focando NO QUE o sistema deve ter em relação a funcionalidades e não focando em COMO o sistema vai fornecer acesso ao usuário a determinada funcionalidade. Por exemplo, o que foi especificado como RF 04 aborda descrições sobre COMO será o funcionamento do sistema, assim como o RF 05.
Não entendi bem o RF 04. Por exemplo, sobre o RF 05, uma forma correta de descrevê-lo seria "O sistema deverá possibilitar a revisão das questões."
